src/routes/OwnerRoutes.py
from collections import namedtuple
from datetime import datetime, timedelta
import secrets
import string
from flask import Blueprint, jsonify, render_template_string, request
from flask_jwt_extended import get_jwt, jwt_required
from flask_mail import Message
from config.mail_conf import mail
from guards.RoutesGuards import with_session, with_transaction


BP_Owner = Blueprint('BP_Owner', __name__)

@BP_Owner.route("/create_employee", methods=["POST"])
@jwt_required()
@with_transaction
def create_employee(cursor):

    jwt_data = get_jwt()

    rfc_comp = jwt_data.get("rfc_comp")
    
    required_fields = ["rol", "rfc", "nombre", "correo", "app", "apm", "fech_nac", "sex", "tel", "id_colonia", "finca_id"]
    missing_fields = [field for field in required_fields if not request.form.get(field)]

    # Validar si falta algún campo
    if missing_fields:
        return jsonify({"error": f"Faltan los siguientes campos: {', '.join(missing_fields)}"}), 400

    rfc = request.form.get("rfc")
    nombre = request.form.get("nombre")
    correo = request.form.get("correo")
    app = request.form.get("app")
    apm = request.form.get("apm")
    fech_nac = request.form.get("fech_nac")
    sex = request.form.get("sex")
    tel = request.form.get("tel")
    rol = request.form.get("rol")
    turno = request.form.get("turno")
    id_colonia = request.form.get("id_colonia")

    password = gn_pass(7)

    query = "INSERT INTO personas (rfc, nombre, correo, app, apm, fech_nac, sex, tel, id_colonia) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);"
    cursor.execute(query, (rfc, nombre, correo, app, apm, fech_nac, sex, tel, id_colonia))

    query = "INSERT INTO usuarios (rfc, pass, rol, rfc_comp) VALUES (%s, %s, %s, %s);"
    cursor.execute(query, (rfc, password, rol, rfc_comp))

    finca_id = request.form.get("finca_id")

    query = "INSERT INTO empleados (rfc, puesto_id, finca_id, turno) VALUES (%s, %s, %s, %s);"
    cursor.execute(query, (rfc, rol, finca_id, turno))
    
    return jsonify({"success": True, "msg": "Usuario creado correctamente"}), 200

def gn_pass(longitud=12):
    caracteres = string.ascii_letters + string.digits + string.punctuation
    return ''.join(secrets.choice(caracteres) for _ in range(longitud))

@BP_Owner.route("/create_finca", methods=["POST"])
@jwt_required()
@with_transaction
def create_finca(cursor):

    jwt_data = get_jwt()
    rfc_comp = jwt_data.get("rfc_comp")
    
    required_fields = ["nombre", "capacidad", "id_colonia"]
    missing_fields = [field for field in required_fields if not request.form.get(field)]

    # Validar si falta algún campo
    if missing_fields:
        return jsonify({"error": f"Faltan los siguientes campos: {', '.join(missing_fields)}"}), 400

    nombre = request.form.get("nombre")
    capacidad = request.form.get("capacidad")
    descrip = request.form.get("descrip")
    id_colonia = request.form.get("id_colonia")

    query = "INSERT INTO fincas (nombre, capacidad, descrip, id_colonia, rfc_comp) VALUES (%s, %s, %s, %s, %s);"
    cursor.execute(query, (nombre, capacidad, descrip, id_colonia, rfc_comp))

    return jsonify({"success": True, "msg": "Finca registrada correctamente"}), 200

@BP_Owner.route("/update_finca/<id_finca>", methods=["PUT"])
@jwt_required()
@with_transaction
def update_finca(cursor, id_finca):
    jwt_data = get_jwt()
    rfc_comp = jwt_data.get("rfc_comp")
    
    required_fields = ["id", "nombre", "capacidad", "descrip", "id_colonia"]
    missing_fields = [field for field in required_fields if not request.form.get(field)]

    # Validar si falta algún campo
    if missing_fields:
        return jsonify({"error": f"Faltan los siguientes campos: {', '.join(missing_fields)}"}), 400
    
    _id = request.form.get("id")
    nombre = request.form.get("nombre")
    capacidad = request.form.get("capacidad")
    descrip = request.form.get("descrip")
    id_colonia = request.form.get("id_colonia")

    query = "UPDATE fincas SET nombre=%s, capacidad=%s, descrip=%s, id_colonia=%s WHERE id=%s;"
    cursor.execute(query, (nombre, capacidad, descrip, id_colonia, _id))

    return jsonify({"success": True, "msg": "Finca actualizada correctamente"}), 200

@BP_Owner.route("/get-all-fincas", methods=["GET"])
@jwt_required()
@with_session
def get_fincas(cursor):

    jwt_data = get_jwt()

    rfc_comp = jwt_data.get("rfc_comp")

    query = "SELECT * FROM fincas WHERE rfc_comp=%s;"
    cursor.execute(query, (rfc_comp,))

    data = convertToObject(cursor)

    return jsonify(data), 200

@BP_Owner.route("/get-all-puestos", methods=["GET"])
@jwt_required()
@with_session
def get_puestos(cursor):

    jwt_data = get_jwt()

    rfc_comp = jwt_data.get("rfc_comp")

    print("ENTRO", rfc_comp)

    query = '''
            SELECT 
            puestos.id AS puesto_id,
            puestos.nombre,
            puestos.descripcion,
            config_puestos.id AS config_id,
            config_puestos.salario_base,
            config_puestos.dias_lab,
            config_puestos.h_ent,
            config_puestos.h_sal,
            config_puestos.rfc_comp
        FROM puestos
        JOIN config_puestos ON config_puestos.id_puesto = puestos.id;
            '''
    cursor.execute(query)

    puestos = cursor.fetchall()
    print(puestos)
    

    puestos = convertToObject(cursor);


    print(puestos)

    return jsonify(puestos), 200

@BP_Owner.route("/update-puesto", methods=["PUT"])
@jwt_required()
@with_transaction
def update_puesto(cursor):

    required_fields = ["id", "salario_base", "h_ent", "h_sal", "dias_lab"]
    missing_fields = [field for field in required_fields if not request.form.get(field)]

    # Validar si falta algún campo
    if missing_fields:
        return jsonify({"error": f"Faltan los siguientes campos: {', '.join(missing_fields)}"}), 400
    
    _id = request.form.get("id")
    salario_base = request.form.get("salario_base")
    h_ent = request.form.get("h_ent")
    h_sal = request.form.get("h_sal")
    dias_lab = request.form.get("dias_lab")

    query = "UPDATE config_puestos SET salario_base=%s, dias_lab=%s, h_ent=%s, h_sal=%s WHERE id=%s;"
    cursor.execute(query, (salario_base, dias_lab, h_ent, h_sal, _id))

    return jsonify("El puesto fue actualizado correctamente."), 200




def convertToObject(cursor):
    columnas = [column[0] for column in cursor.description]  # Obtener nombres de columnas
    TABLE = namedtuple('TABLE', columnas)  # Crear namedtuple
    response = cursor.fetchall()

    object_data = [TABLE(*row) for row in response]  # Convertir filas en objetos

    def serialize_value(value):
        """Convierte valores no serializables a formatos compatibles con JSON"""
        if isinstance(value, timedelta):  # Si es un TIME de MySQL (timedelta)
            # Convertir timedelta a horas y minutos en formato 24H (HH:MM)
            total_seconds = value.total_seconds()
            hours = int(total_seconds // 3600)  # Horas
            minutes = int((total_seconds % 3600) // 60)  # Minutos
            return f"{hours:02d}:{minutes:02d}"  # Formato HH:MM (24H)

        return value  # Devolver el valor normal si no es timedelta

    return [{key: serialize_value(value) for key, value in obj._asdict().items()} for obj in object_data]

src/templates/owner/admin/fincas/regis.html
{% extends 'owner/panel.html' %}

{% block title_bar %} Nueva finca {% endblock %}

{% block cont_dash %}
<form id="regForm" action="{{ url_for('BP_Owner.create_finca') }}" method="POST" style="padding: 2%">
    
    <div style="margin-top: 3vh; margin-bottom: 3vh">
        <label>Datos de la finca</label>
        <hr />
    </div>

    <div class="sam-form-container">
        <div class="sam-form-field">
            <input type="text" id="nombre" placeholder=" " name="nombre" required />
            <label class="itim-regular"> Nombre</label>
        </div>

        <div class="sam-form-field">
            <input type="number" id="capacidad" placeholder=" " name="capacidad" required />
            <label class="itim-regular">Capacidad máxima de ganados</label>
        </div>

        <div class="sam-form-field">
            <input type="text" id="descrip" placeholder=" " name="descrip" />
            <label class="itim-regular">(Opcional) - Descripción de la finca</label>
        </div>
    </div>

    <div style="margin-top: 3vh; margin-bottom: 3vh">
        <label>Ubicación</label>
        <hr />
    </div>

    <div class="sam-form-container">
        <div class="sam-form-field">
            <select id="paises" name="paises" required onchange="selectPais()">
                <option value="" disabled selected>Selecciona el pais</option>
            </select>
        </div>
        <div class="sam-form-field">
            <select id="estados" name="estados" required onchange="selectEstado()" disabled="true">
                <option value="" disabled selected>Selecciona el estado</option>
            </select>
        </div>
        <div class="sam-form-field">
            <select id="municipios" name="municipios" required onchange="selectMunicipio()" disabled="true">
                <option value="" disabled selected>Selecciona el municipio</option>
            </select>
        </div>

        <div class="sam-form-field">
            <select id="id_colonia" name="id_colonia" required disabled="true">
                <option value="" disabled selected>Selecciona la colonia</option>
            </select>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Registrar</button>
</form>

<script>
    addSwalAlertCre("regForm", "/create_finca");
    function addSwalAlertCre(id, endpoint) {
        document.getElementById(id).addEventListener("submit", function (event) {
        event.preventDefault(); // Evita que la página se recargue

        let formData = new FormData(this);

        fetch(endpoint, {
            method: "POST",
            body: formData,
            headers: {
                Authorization: "Bearer " + token,
            },
        })
        .then((response) => {
            if (response.status === 401) {
                // Si el token ha expirado
                return response.json().then((data) => {
                    Swal.fire({
                        title: "Sesión expirada",
                        text: data.error,
                        icon: "info",
                        confirmButtonText: "Aceptar",
                    }).then(() => {
                        window.location.href = "/"; // Redirige después del alert
                    });
                });
            } else if (response.status === 400) {
                // Si es 400
                return response.json().then((data) => {
                    Swal.fire({
                        title: "Un error a ocurrido",
                        text: data.error,
                        icon: "warning",
                        confirmButtonText: "Aceptar",
                    });
                });
            } else if (response.status === 200) {
                // Si es 400
                return response.json().then((data) => {
                    document.getElementById("regForm").reset();
                    Swal.fire({
                        title: "Nueva finca registrada",
                        text: data.msg,
                        icon: "success",
                    });
                });
            }
        })
        .then((data) => { });
    });
    }

    fetch("/get-paises", { method: "GET" })
        .then((response) => response.json())
        .then((data) => {
            console.log(data);
            // Llenar el select con las opciones de los países
            let selectPais = document.getElementById("paises");
            data.forEach((estado) => {
                let option = document.createElement("option");
                option.value = estado.id;
                option.textContent = estado.nom;
                selectPais.appendChild(option);
            });
        });

        fetch("/get-all-fincas", { 
            method: "GET",
            headers: { "Authorization": "Bearer " + token }
        })
        .then((response) => response.json())
        .then((data) => {
            console.log(data);
            // Llenar el select con las opciones de los países
            let fincas = document.getElementById("finca_id");
            data.forEach((finca) => {
                let option = document.createElement("option");
                option.value = estado.id;
                option.textContent = estado.nombre;
                fincas.appendChild(option);
            });
        });

    // ################ SE CARGAN LOS DATOS DE LOS PAISES ################

    function selectPais() {
        let selectElement = document.getElementById("paises");
        let pais_id = selectElement.value;

        fetch("/get-estados/" + pais_id, {
            method: "GET",
        })
            .then((response) => response.json())
            .then((data) => {
                console.log(data);
                // Llenar el select con las opciones de los países
                let selectEst = document.getElementById("estados");
                selectEst.innerHTML =
                    '<option value="" disabled selected>Selecciona el estado</option>';
                data.forEach((estado) => {
                    let option = document.createElement("option");
                    option.value = estado.id;
                    option.textContent = estado.nom;
                    selectEst.appendChild(option);
                });
                selectEst.disabled = false;
            });
    }

    // ################ SE CARGAN LOS DATOS DE LOS ESTADOS ################

    function selectEstado() {
        let selectElement = document.getElementById("estados");
        let estado_id = selectElement.value;

        fetch("/get-municipios/" + estado_id, {
            method: "GET",
        })
            .then((response) => response.json())
            .then((data) => {
                console.log(data);
                // Llenar el select con las opciones de los países
                let selectMun = document.getElementById("municipios");
                selectMun.innerHTML =
                    '<option value="" disabled selected>Selecciona el municipio</option>';
                data.forEach((mun) => {
                    let option = document.createElement("option");
                    option.value = mun.id;
                    option.textContent = mun.nom;
                    selectMun.appendChild(option);
                });
                selectMun.disabled = false;
            });
    }

    function selectMunicipio() {
        let selectElement = document.getElementById("municipios");
        let mun_id = selectElement.value;

        fetch("/get-colonias/" + mun_id, {
            method: "GET",
        })
            .then((response) => response.json())
            .then((data) => {
                console.log(data);
                // Llenar el select con las opciones de los países
                let selectCol = document.getElementById("id_colonia");
                selectCol.innerHTML =
                    '<option value="" disabled selected>Selecciona la colonia</option>';
                data.forEach((col) => {
                    let option = document.createElement("option");
                    option.value = col.id;
                    option.textContent = col.nom;
                    selectCol.appendChild(option);
                });
                selectCol.disabled = false;
            });
    }

</script>

{% endblock %}

src/templates/owner/admin/fincas/view.html
{% extends 'owner/panel.html' %}


{% block title_bar %}
<div class="d-flex align-items-center">
    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#FFFFFF"><path d="M200-200h80v-80h-80v80Zm160 0h80v-80h-80v80Zm160 0h80v-80h-80v80Zm160 0h80v-80h-80v80ZM200-680h80v-80h-80v80Zm0 160h80v-80h-80v80Zm0 160h80v-80h-80v80Zm160-320h80v-80h-80v80Zm0 160h80v-80h-80v80Zm0 160h80v-80h-80v80Zm160-320h80v-80h-80v80Zm0 160h80v-80h-80v80Zm0 160h80v-80h-80v80Zm160-320h80v-80h-80v80Zm0 160h80v-80h-80v80Zm0 160h80v-80h-80v80ZM200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Z"/></svg>
    <label style="margin-left: 2vh;">Fincas</label>
</div>
{% endblock %}

{% block cont_dash %}

<style>
    .container {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
        gap: 20px;
        max-width: 1200px;
        margin: 0 auto;
    }

    .card {
        background-color: #fff;
        border-radius: 12px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        transition: transform 0.3s, box-shadow 0.3s;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 10px 15px rgba(0, 0, 0, 0.2);
    }

    .card-title {
        font-size: 1.4em;
        color: #34495e;
        display: flex;
        margin-bottom: 10px;
    }

    .card-capacidad {
        font-size: 1em;
        color: #27ae60;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .card-desc {
        font-size: 0.95em;
        color: #555;
        margin-bottom: 10px;
    }

    .card-direccion {
        font-size: 0.9em;
        color: #7f8c8d;
    }
    .sam-form-field {
        height: fit-content;
    }
    .sam-form-field input{
        font-size: 14px;
        height: fit-content;
    }
    input, textarea {
        border: 2px solid rgba(122, 112, 86, 0.309);
        border-radius: 5px;
        font-weight: 600;
    }
    input:disabled, textarea:disabled{
        background-color: white;
        border: 2px solid rgb(255, 255, 255);
    }

    .change {
        font-size: 10px;
        font-weight: 600;
        display: none;
    }

    @media (max-width: 600px) {
        .card-title {
            font-size: 1.2em;
        }

        .card-capacidad {
            font-size: 0.95em;
        }
    }
</style>

<script>
    function redirect(ruta) {
        window.location.href = ruta;
    }

    function addSwalAlert(id, endpoint) {
    document.getElementById("regForm_"+id).addEventListener("submit", function (event) {
    event.preventDefault(); // Evita que la página se recargue

    let formData = new FormData(this);

    fetch(endpoint, {
        method: "PUT",
        body: formData,
        headers: {
            Authorization: "Bearer " + token,
        },
    })
    .then((response) => {
        if (response.status === 401) {
            // Si el token ha expirado
            return response.json().then((data) => {
                Swal.fire({
                    title: "Sesión expirada",
                    text: data.error,
                    icon: "info",
                    confirmButtonText: "Aceptar",
                }).then(() => {
                    window.location.href = "/"; // Redirige después del alert
                });
            });
        } else if (response.status === 400) {
            // Si es 400
            return response.json().then((data) => {
                Swal.fire({
                    title: "Un error a ocurrido",
                    text: data.error,
                    icon: "warning",
                    confirmButtonText: "Aceptar",
                });
            });
        } else if (response.status === 200) {
            // Si es 200
            return response.json().then((data) => {
                Swal.fire({
                    title: "Actualizado",
                    text: data.msg,
                    icon: "success",
                });
                let EDIT = document.getElementById("edit_"+id);
                let SAVE = document.getElementById("save_"+id);
                let btn_cp = document.getElementById("btn_cp_"+id);

                EDIT.style.display = 'block';
                SAVE.style.display = 'none';
                btn_cp.style.display = 'none';


                // Selecciona todos los elementos con la clase "ocultar-label"
                const input_edit = document.querySelectorAll('.i_edit_'+id);

                // Recorre la lista y muestra cada uno
                input_edit.forEach(inpt => {
                    inpt.setAttribute('disabled', true);
                });
            });
        }
    })
    .then((data) => { });
});
}


</script>

<div style="padding: 20px; padding-top: 0px;" onclick="redirect('/dashboard/owner/register-finca')">
    <button class="btn btn-info w-full" style="padding: 15px; font-weight: 600; font-family:Arial, Helvetica, sans-serif;">Registrar nueva finca</button>
</div>
<div class="container">
    {% for finca in fincas %}
    <div class="card">
        <form id="regForm_{{ finca.id }}">
            <input style="display: none;" type="number" id="id" name="id"  value="{{finca.id}}">
            <input style="display: none;" type="number" id="id_colonia_{{finca.id}}" name="id_colonia"  value="{{finca.id_colonia.id}}">
            <div class="card-title">
                <div style="width: 100%;">
                    <input class="i_edit_{{ finca.id }}" type="text" id="nombre" placeholder=" " name="nombre" disabled required value="{{ finca.nombre }}"/>
                </div>
            </div>
            <div class="card-capacidad">
                <label class="l_input_{{ finca.id }}" style="color: #34495e;">
                    Capacidad MAX: 
                    <input class="i_edit_{{ finca.id }}" type="number" id="capacidad" placeholder=" " name="capacidad" disabled required value="{{ finca.capacidad }}"  style="width: 80px;"/>
                    </label>
                <label for="">Ganados en finca: 12</label><br/>
                <label for="">Disponible: 12</label>
            </div>
            <div class="card-desc">
                <textarea class="i_edit_{{ finca.id }}" name="descrip" id="descrip" disabled style="width: 100%;" required>{{ finca.descrip }}</textarea>
                </div>
            <div class="card-direccion">
                <label class="l_input_{{ finca.id }}" id="direct_{{ finca.id }}">{{ finca.id_colonia.name }}</label> <button class="change btn btn-warning" id="btn_cp_{{ finca.id }}" onclick="change('{{finca.id}}')" type="button">Buscar por Código Postal</button>
            </div>
            <button class="btn btn-warning" type="button" style="margin-top: 20px; width: 100%; min-width: 50px;" onclick="edit('{{finca.id}}')" id="edit_{{finca.id}}">Editar</button>
            <div id="save_{{finca.id}}" style="display: none; width: 100%; justify-content: center; gap: 1vh; margin-top: 20px;">
                <button class="btn btn-success w-full" type="submit">Guardar</button>
                <button class="btn btn-danger w-full" type="button" onclick="cancel('{{finca.id}}')">Cancelar</button>
            </div>
        </form>
    </div>
    <script>
        addSwalAlert("{{ finca.id }}", "/update_finca/{{finca.id}}");
    </script>
    {% endfor %}
</div>
<script>

function edit(id) {    
    console.log("Entro",id);
    let EDIT = document.getElementById("edit_"+id);
    let SAVE = document.getElementById("save_"+id);
    let btn_cp = document.getElementById("btn_cp_"+id);

    EDIT.style.display = 'none';
    SAVE.style.display = 'flex';
    btn_cp.style.display = 'flex';

    // Selecciona todos los elementos con la clase "ocultar-label"
    const input_edit = document.querySelectorAll('.i_edit_'+id);

    // Recorre la lista y muestra cada uno
    input_edit.forEach(inpt => {
        inpt.removeAttribute('disabled');
    });
}

function cancel(id) {    
    console.log("Entro",id);
    let EDIT = document.getElementById("edit_"+id);
    let SAVE = document.getElementById("save_"+id);
    let btn_cp = document.getElementById("btn_cp_"+id);

    EDIT.style.display = 'block';
    SAVE.style.display = 'none';
    btn_cp.style.display = 'none';

    // Selecciona todos los elementos con la clase "ocultar-label"
    const input_edit = document.querySelectorAll('.i_edit_'+id);

    // Recorre la lista y muestra cada uno
    input_edit.forEach(inpt => {
        inpt.setAttribute('disabled', true);
    });
}

function change(id) {
    let dirComplt = "";
    Swal.fire({
  title: "Buscar por código postal",
  input: "number",
  inputAttributes: {
    autocapitalize: "off"
  },
  showCancelButton: true,
  confirmButtonText: "Buscar",
  showLoaderOnConfirm: true,
  preConfirm: async (cp) => {
    try {
      const url = `/get-col-by-cp/${cp}`;

      const response = await fetch(url);
      if (!response.ok) {
        return Swal.showValidationMessage(`${JSON.stringify(await response.json())}`);
      }
      
      let res = await response.json();
      dirComplt = res.mun +", "+res.est+". CP: "+cp+". "
      console.log("GET-COL",res);
      return res;
    } catch (error) {
      Swal.showValidationMessage(`Request failed: ${error}`);
    }
  },
  allowOutsideClick: () => !Swal.isLoading()
}).then((result) => {
  if (result.isConfirmed) {
    let colonias = result.value.colonias;
    let htmlbody = `
  <div class="sam-form-container">
    <div class="sam-form-field">
        <input type="text" id="estado" placeholder=" " name="estado" disabled required value='${result.value.est}' />
        <label class="itim-regular">Estado</label>
    </div>

    <div class="sam-form-field">
        <input type="text" id="mun" placeholder=" " name="mun" disabled required value='${result.value.mun}' />
        <label class="itim-regular">Municipio</label>
    </div>
            <div class="sam-form-field">
                <select id="select_col" required onchange="selectDirect()">`;
    colonias.forEach(element => {
        htmlbody += "<option value='"+element.id+"|"+element.nom+"'>"+element.nom+"</option>"
    });
    
    htmlbody += `</select></div></div>`

    name_change_col = colonias[0].nom;
    id_change_col = colonias[0].id;

    console.log("ID_COL:", id_change_col, "NOM_COL", name_change_col)


    Swal.fire({
        title: "<strong>Verifica y completa el domicilio.</strong>",
        html: htmlbody,
        showCloseButton: true,
        showCancelButton: true,
        focusConfirm: false,
        confirmButtonText: `
            <i class="fa fa-thumbs-up"></i> Listo
        `,
        confirmButtonAriaLabel: "Thumbs up, great!",
        cancelButtonText: `
            <i class="fa fa-thumbs-down">Cancelar</i>
        `,
        cancelButtonAriaLabel: "Thumbs down"
    }).then((result) => {
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
            console.log("Confirmo")
            let id_colonia = document.getElementById("id_colonia_"+id);
            id_colonia.value = id_change_col;
            dirComplt += name_change_col+".";
            let element = document.getElementById("direct_"+id);
            element.innerText = dirComplt;
            console.log("RESULTADO: ", dirComplt)
        }
    });
  }
});
}

let id_change_col;
let name_change_col;

function selectDirect(){
    let selectElement = document.getElementById("select_col");
    const partes = selectElement.value.split('|');
    id_change_col = partes[0];
    name_change_col = partes[1];
}
</script>
{% endblock %}