src/routes/SuperUserRoutes.py
from datetime import date, datetime, time
import secrets
import string
from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required
from database.db import *

import os

from guards.RoutesGuards import with_transaction

# Cargar variables desde el archivo .env
load_dotenv()

BP_SuperUserRoutes = Blueprint('BP_SuperUserRoutes', __name__)

@BP_SuperUserRoutes.route('/create_owner', methods=["POST"])
@jwt_required()
@with_transaction
def create_owner(cursor):

    required_fields = ["rfc_comp", "nom_comp", "rfc", "nombre", "correo", "app", "apm", "fech_nac", "sex", "tel", "id_colonia"]
    missing_fields = [field for field in required_fields if not request.form.get(field)]

    # Validar si falta algún campo
    if missing_fields:
        return jsonify({"error": f"Faltan los siguientes campos: {', '.join(missing_fields)}"}), 400
    
    rfc_comp = request.form.get("rfc_comp")
    nom_comp = request.form.get("nom_comp")
    
    query = "INSERT INTO companies (rfc_comp, nom) VALUES (%s, %s);"
    cursor.execute(query, (rfc_comp, nom_comp))

    rfc = request.form.get("rfc")
    nombre = request.form.get("nombre")
    correo = request.form.get("correo")
    app = request.form.get("app")
    apm = request.form.get("apm")
    fech_nac = request.form.get("fech_nac")
    sex = request.form.get("sex")
    tel = request.form.get("tel")
    id_colonia = request.form.get("id_colonia")

    
    query = "INSERT INTO personas (rfc, nombre, correo, app, apm, fech_nac, sex, tel, id_colonia) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);"
    cursor.execute(query, (rfc, nombre, correo, app, apm, fech_nac, sex, tel, id_colonia))

    query = "INSERT INTO usuarios (rfc, pass, rol, rfc_comp) VALUES (%s, %s, %s, %s);"
    cursor.execute(query, (rfc, gn_pass(7), 0, rfc_comp))
    
    hora = datetime.now().time()
    query = "INSERT INTO config_puestos (id_puesto, salario_base, dias_lab, h_ent, h_sal, rfc_comp) VALUES (%s, %s, %s, %s, %s, %s);"
    cursor.execute(query, (1, 0, "", hora, hora, rfc_comp))
    cursor.execute(query, (2, 0, "", hora, hora, rfc_comp))
    cursor.execute(query, (3, 0, "", hora, hora, rfc_comp))
    cursor.execute(query, (4, 0, "", hora, hora, rfc_comp))
    
    return jsonify({"success": True, "msg": "Usuario creado correctamente"}), 200

def gn_pass(longitud=12):
    caracteres = string.ascii_letters + string.digits + string.punctuation
    return ''.join(secrets.choice(caracteres) for _ in range(longitud))

src/templates/superuser/metrics.html
{% extends 'dashboard.html' %}

{% block sidenavbar %}
<li class="mb-4"><a href="/dashboard/superuser/metrics" class="block p-2 rounded hover:bg-blue-500">Métricas del sitio</a></li>
<li class="mb-4"><a href="/dashboard/superuser/register" class="block p-2 rounded hover:bg-blue-500">Registrar cliente</a></li>
<li class="mb-4"><a href="/dashboard/superuser/settings" class="block p-2 rounded hover:bg-blue-500">Ajustes</a></li>
{% endblock %}

{% block cont_dash %}
<!-- CABECERA CON LAS MÉTRICAS GENERALES -->
<div class="container text-center" style="margin-bottom: 5vh;">
    <div style="display: flex; width: 100%; flex-direction: row; justify-content: center; gap: 3vh; flex-wrap: wrap;">

    <!-- VISITAS AL SITIO -->
    <div class="tar_cont">
    <div class="tar_center">
    <div class="bg-1 tar_row">
        <div class="tar_row_left">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="M480-320q75 0 127.5-52.5T660-500q0-75-52.5-127.5T480-680q-75 0-127.5 52.5T300-500q0 75 52.5 127.5T480-320Zm0-72q-45 0-76.5-31.5T372-500q0-45 31.5-76.5T480-608q45 0 76.5 31.5T588-500q0 45-31.5 76.5T480-392Zm0 192q-146 0-266-81.5T40-500q54-137 174-218.5T480-800q146 0 266 81.5T920-500q-54 137-174 218.5T480-200Zm0-300Zm0 220q113 0 207.5-59.5T832-500q-50-101-144.5-160.5T480-720q-113 0-207.5 59.5T128-500q50 101 144.5 160.5T480-280Z"/></svg>
        <label class="poppins-light">Visitas hoy</label>
        </div>
        <div class="tar_row_right">
        <label class="poppins-light">32</label>
        </div>
    </div>
    </div>
    </div>

    <!-- USUARIOS ÚNICOS -->
    <div class="tar_cont">
        <div class="tar_center">
        <div class="bg-2 tar_row">
        <div class="tar_row_left">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#FFFFFF"><path d="M40-160v-112q0-34 17.5-62.5T104-378q62-31 126-46.5T360-440q66 0 130 15.5T616-378q29 15 46.5 43.5T680-272v112H40Zm720 0v-120q0-44-24.5-84.5T666-434q51 6 96 20.5t84 35.5q36 20 55 44.5t19 53.5v120H760ZM360-480q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47Zm400-160q0 66-47 113t-113 47q-11 0-28-2.5t-28-5.5q27-32 41.5-71t14.5-81q0-42-14.5-81T544-792q14-5 28-6.5t28-1.5q66 0 113 47t47 113ZM120-240h480v-32q0-11-5.5-20T580-306q-54-27-109-40.5T360-360q-56 0-111 13.5T140-306q-9 5-14.5 14t-5.5 20v32Zm240-320q33 0 56.5-23.5T440-640q0-33-23.5-56.5T360-720q-33 0-56.5 23.5T280-640q0 33 23.5 56.5T360-560Zm0 320Zm0-400Z"/></svg>                        <label class="poppins-light">Usuarios únicos hoy</label>
        </div>
        <div class="tar_row_right">
            <label class="poppins-light">12</label>
        </div>
        </div>
        </div>
    </div>

    <!-- TASA DE REBOTE -->
    <div class="tar_cont">
        <div class="tar_center">
        <div class="bg-4 tar_row">
        <div class="tar_row_left">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#FFFFFF"><path d="M760-200v-160q0-50-35-85t-85-35H273l144 144-57 56-240-240 240-240 57 56-144 144h367q83 0 141.5 58.5T840-360v160h-80Z"/></svg>                        <label class="poppins-light">Tasa de rebote</label>
        </div>
        <div class="tar_row_right">
            <label class="poppins-light">23%</label>
        </div>
        </div>
        </div>
    </div>

    <!-- TASA DE RETENCIÓN -->
    <div class="tar_cont">
        <div class="tar_center">
        <div class="bg-5 tar_row">
        <div class="tar_row_left">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#FFFFFF"><path d="M480-800q-33 0-56.5-23.5T400-880q0-33 23.5-56.5T480-960q33 0 56.5 23.5T560-880q0 33-23.5 56.5T480-800ZM360-200v-480q-60-5-122-15t-118-25l20-80q78 21 166 30.5t174 9.5q86 0 174-9.5T820-800l20 80q-56 15-118 25t-122 15v480h-80v-240h-80v240h-80ZM320 0q-17 0-28.5-11.5T280-40q0-17 11.5-28.5T320-80q17 0 28.5 11.5T360-40q0 17-11.5 28.5T320 0Zm160 0q-17 0-28.5-11.5T440-40q0-17 11.5-28.5T480-80q17 0 28.5 11.5T520-40q0 17-11.5 28.5T480 0Zm160 0q-17 0-28.5-11.5T600-40q0-17 11.5-28.5T640-80q17 0 28.5 11.5T680-40q0 17-11.5 28.5T640 0Z"/></svg>                        <label class="poppins-light">Tasa de retención</label>
        </div>
        <div class="tar_row_right">
            <label class="poppins-light">65%</label>
        </div>
        </div>
        </div>
    </div>


    </div>
</div>
{% endblock %}

src/templates/superuser/register.html
{% extends 'dashboard.html' %} {% block sidenavbar %}
<li class="mb-4">
  <a
    href="/dashboard/superuser/metrics"
    class="block p-2 rounded hover:bg-blue-500"
    >Métricas del sitio</a
  >
</li>
<li class="mb-4">
  <a
    href="/dashboard/superuser/register"
    class="block p-2 rounded hover:bg-blue-500"
    >Registrar cliente</a
  >
</li>
<li class="mb-4">
  <a
    href="/dashboard/superuser/settings"
    class="block p-2 rounded hover:bg-blue-500"
    >Ajustes</a
  >
</li>
{% endblock %} {% block cont_dash %}
<form
  id="regForm"
  action="{{ url_for('BP_SuperUserRoutes.create_owner') }}"
  method="POST"
  style="padding: 2%"
>
  <div style="margin-bottom: 3vh">
    <label>Datos del dueño</label>
    <hr />
  </div>
  <!-- DATOS IMPORTANTES DE CONETACTO DEL DUEÑO -->
  <div class="sam-form-container">
    <div class="sam-form-field">
      <input type="text" id="rfc" placeholder=" " name="rfc" required />
      <label class="itim-regular">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          height="24px"
          viewBox="0 -960 960 960"
          width="24px"
          fill="#e8eaed"
        >
          <path
            d="M481-781q106 0 200 45.5T838-604q7 9 4.5 16t-8.5 12q-6 5-14 4.5t-14-8.5q-55-78-141.5-119.5T481-741q-97 0-182 41.5T158-580q-6 9-14 10t-14-4q-7-5-8.5-12.5T126-602q62-85 155.5-132T481-781Zm0 94q135 0 232 90t97 223q0 50-35.5 83.5T688-257q-51 0-87.5-33.5T564-374q0-33-24.5-55.5T481-452q-34 0-58.5 22.5T398-374q0 97 57.5 162T604-121q9 3 12 10t1 15q-2 7-8 12t-15 3q-104-26-170-103.5T358-374q0-50 36-84t87-34q51 0 87 34t36 84q0 33 25 55.5t59 22.5q34 0 58-22.5t24-55.5q0-116-85-195t-203-79q-118 0-203 79t-85 194q0 24 4.5 60t21.5 84q3 9-.5 16T208-205q-8 3-15.5-.5T182-217q-15-39-21.5-77.5T154-374q0-133 96.5-223T481-687Zm0-192q64 0 125 15.5T724-819q9 5 10.5 12t-1.5 14q-3 7-10 11t-17-1q-53-27-109.5-41.5T481-839q-58 0-114 13.5T260-783q-8 5-16 2.5T232-791q-4-8-2-14.5t10-11.5q56-30 117-46t124-16Zm0 289q93 0 160 62.5T708-374q0 9-5.5 14.5T688-354q-8 0-14-5.5t-6-14.5q0-75-55.5-125.5T481-550q-76 0-130.5 50.5T296-374q0 81 28 137.5T406-123q6 6 6 14t-6 14q-6 6-14 6t-14-6q-59-62-90.5-126.5T256-374q0-91 66-153.5T481-590Zm-1 196q9 0 14.5 6t5.5 14q0 75 54 123t126 48q6 0 17-1t23-3q9-2 15.5 2.5T744-191q2 8-3 14t-13 8q-18 5-31.5 5.5t-16.5.5q-89 0-154.5-60T460-374q0-8 5.5-14t14.5-6Z"
          />
        </svg>
        RFC del dueño</label
      >
    </div>

    <div class="sam-form-field">
      <input type="email" id="correo" placeholder=" " name="correo" required />
      <label class="itim-regular">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          height="24px"
          viewBox="0 -960 960 960"
          width="24px"
          fill="#000000"
        >
          <path
            d="M160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h640q33 0 56.5 23.5T880-720v480q0 33-23.5 56.5T800-160H160Zm320-280L160-640v400h640v-400L480-440Zm0-80 320-200H160l320 200ZM160-640v-80 480-400Z"
          />
        </svg>
        Correo eléctronico</label
      >
    </div>

    <div class="sam-form-field">
      <input type="number" id="tel" placeholder=" " name="tel" required />
      <label class="itim-regular">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          height="24px"
          viewBox="0 -960 960 960"
          width="24px"
          fill="#000000"
        >
          <path
            d="M798-120q-125 0-247-54.5T329-329Q229-429 174.5-551T120-798q0-18 12-30t30-12h162q14 0 25 9.5t13 22.5l26 140q2 16-1 27t-11 19l-97 98q20 37 47.5 71.5T387-386q31 31 65 57.5t72 48.5l94-94q9-9 23.5-13.5T670-390l138 28q14 4 23 14.5t9 23.5v162q0 18-12 30t-30 12ZM241-600l66-66-17-94h-89q5 41 14 81t26 79Zm358 358q39 17 79.5 27t81.5 13v-88l-94-19-67 67ZM241-600Zm358 358Z"
          />
        </svg>
        Teléfono</label
      >
    </div>
  </div>

  <div class="sam-form-container">
    <div class="sam-form-field">
      <input type="text" id="nombe" placeholder=" " name="nombre" required />
      <label class="itim-regular">Nombre(s)</label>
    </div>
    <div class="sam-form-field">
      <input type="text" id="app" placeholder=" " name="app" required />
      <label class="itim-regular">Apellido paterno</label>
    </div>
    <div class="sam-form-field">
      <input type="text" id="apm" placeholder=" " name="apm" required />
      <label class="itim-regular">Apellido materno</label>
    </div>

    <div class="sam-form-field">
      <select id="sex" name="sex" required>
        <option value="" selected disabled>Género</option>
        <option value="M">Masculino</option>
        <option value="F">Femenino</option>
      </select>
    </div>
    <div class="sam-form-field">
      <select id="paises" name="paises" required onchange="selectPais()">
        <option value="" disabled selected>Selecciona el pais</option>
      </select>
    </div>
    <div class="sam-form-field">
      <select
        id="estados"
        name="estados"
        required
        onchange="selectEstado()"
        hidden="true"
      >
        <option value="" disabled selected>Selecciona el estado</option>
      </select>
    </div>
    <div class="sam-form-field">
      <select
        id="municipios"
        name="municipios"
        required
        onchange="selectMunicipio()"
        hidden="true"
      >
        <option value="" disabled selected>Selecciona el municipio</option>
      </select>
    </div>

    <div class="sam-form-field">
      <select id="id_colonia" name="id_colonia" required hidden="true">
        <option value="" disabled selected>Selecciona la colonia</option>
      </select>
    </div>
  </div>

  <div style="margin-top: 3vh; margin-bottom: 3vh">
    <label>Datos de la compañia</label>
    <hr />
  </div>

  <!-- DATOS DE LA COMPAÑIA DEL DUEÑO -->
  <div class="sam-form-container">
    <div class="sam-form-field">
      <input
        type="text"
        id="rfc_comp"
        placeholder=" "
        name="rfc_comp"
        required
      />
      <label class="itim-regular">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          height="24px"
          viewBox="0 -960 960 960"
          width="24px"
          fill="#e8eaed"
        >
          <path
            d="M481-781q106 0 200 45.5T838-604q7 9 4.5 16t-8.5 12q-6 5-14 4.5t-14-8.5q-55-78-141.5-119.5T481-741q-97 0-182 41.5T158-580q-6 9-14 10t-14-4q-7-5-8.5-12.5T126-602q62-85 155.5-132T481-781Zm0 94q135 0 232 90t97 223q0 50-35.5 83.5T688-257q-51 0-87.5-33.5T564-374q0-33-24.5-55.5T481-452q-34 0-58.5 22.5T398-374q0 97 57.5 162T604-121q9 3 12 10t1 15q-2 7-8 12t-15 3q-104-26-170-103.5T358-374q0-50 36-84t87-34q51 0 87 34t36 84q0 33 25 55.5t59 22.5q34 0 58-22.5t24-55.5q0-116-85-195t-203-79q-118 0-203 79t-85 194q0 24 4.5 60t21.5 84q3 9-.5 16T208-205q-8 3-15.5-.5T182-217q-15-39-21.5-77.5T154-374q0-133 96.5-223T481-687Zm0-192q64 0 125 15.5T724-819q9 5 10.5 12t-1.5 14q-3 7-10 11t-17-1q-53-27-109.5-41.5T481-839q-58 0-114 13.5T260-783q-8 5-16 2.5T232-791q-4-8-2-14.5t10-11.5q56-30 117-46t124-16Zm0 289q93 0 160 62.5T708-374q0 9-5.5 14.5T688-354q-8 0-14-5.5t-6-14.5q0-75-55.5-125.5T481-550q-76 0-130.5 50.5T296-374q0 81 28 137.5T406-123q6 6 6 14t-6 14q-6 6-14 6t-14-6q-59-62-90.5-126.5T256-374q0-91 66-153.5T481-590Zm-1 196q9 0 14.5 6t5.5 14q0 75 54 123t126 48q6 0 17-1t23-3q9-2 15.5 2.5T744-191q2 8-3 14t-13 8q-18 5-31.5 5.5t-16.5.5q-89 0-154.5-60T460-374q0-8 5.5-14t14.5-6Z"
          />
        </svg>
        RFC de la compañia</label
      >
    </div>
    <div class="sam-form-field">
      <input
        type="text"
        id="nom_comp"
        placeholder=" "
        name="nom_comp"
        required
      />
      <label class="itim-regular">Nombre comercial</label>
    </div>
  </div>

  <button class="btn btn-primary" color="primary" type="submit">
    Registrar
  </button>
</form>

<script>
  fetch("/get-paises", { method: "GET" })
    .then((response) => response.json())
    .then((data) => {
      console.log(data);
      // Llenar el select con las opciones de los países
      let selectPais = document.getElementById("paises");
      data.forEach((estado) => {
        let option = document.createElement("option");
        option.value = estado.id;
        option.textContent = estado.nom;
        selectPais.appendChild(option);
      });
    });

  // ################ SE CARGAN LOS DATOS DE LOS PAISES ################

  function selectPais() {
    let selectElement = document.getElementById("paises");
    let pais_id = selectElement.value;

    fetch("/get-estados/" + pais_id, {
      method: "GET",
    })
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        // Llenar el select con las opciones de los países
        let selectEst = document.getElementById("estados");
        selectEst.innerHTML =
          '<option value="" disabled selected>Selecciona el estado</option>';
        data.forEach((estado) => {
          let option = document.createElement("option");
          option.value = estado.id;
          option.textContent = estado.nom;
          selectEst.appendChild(option);
        });
        selectEst.hidden = false;
      });
  }

  // ################ SE CARGAN LOS DATOS DE LOS ESTADOS ################

  function selectEstado() {
    let selectElement = document.getElementById("estados");
    let estado_id = selectElement.value;

    fetch("/get-municipios/" + estado_id, {
      method: "GET",
    })
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        // Llenar el select con las opciones de los países
        let selectMun = document.getElementById("municipios");
        selectMun.innerHTML =
          '<option value="" disabled selected>Selecciona el municipio</option>';
        data.forEach((mun) => {
          let option = document.createElement("option");
          option.value = mun.id;
          option.textContent = mun.nom;
          selectMun.appendChild(option);
        });
        selectMun.hidden = false;
      });
  }

  function selectMunicipio() {
    let selectElement = document.getElementById("municipios");
    let mun_id = selectElement.value;

    fetch("/get-colonias/" + mun_id, {
      method: "GET",
    })
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        // Llenar el select con las opciones de los países
        let selectCol = document.getElementById("id_colonia");
        selectCol.innerHTML =
          '<option value="" disabled selected>Selecciona la colonia</option>';
        data.forEach((col) => {
          let option = document.createElement("option");
          option.value = col.id;
          option.textContent = col.nom;
          selectCol.appendChild(option);
        });
        selectCol.hidden = false;
      });
  }

  addSwalAlertCre("regForm", "/create_owner");
  function addSwalAlertCre(id, endpoint, url_redir) {
    document.getElementById(id).addEventListener("submit", function (event) {
      event.preventDefault(); // Evita que la página se recargue

      let formData = new FormData(this);

      fetch(endpoint, {
        method: "POST",
        headers: {
          Authorization: "Bearer " + token,
        },
        body: formData,
      })
        .then((response) => {
          if (response.status === 401) {
            // Si el token ha expirado
            return response.json().then((data) => {
              Swal.fire({
                title: "Sesión expirada",
                text: data.error,
                icon: "info",
                confirmButtonText: "Aceptar",
              }).then(() => {
                window.location.href = "/"; // Redirige después del alert
              });
            });
          } else if (response.status === 400) {
            // Si es 400
            return response.json().then((data) => {
              Swal.fire({
                title: "Un error a ocurrido",
                text: data.error,
                icon: "warning",
                confirmButtonText: "Aceptar",
              });
            });
          } else if (response.status === 200) {
            // Si es 400
            return response.json().then((data) => {
              document.getElementById("regForm").reset();
              Swal.fire({
                title: "Nuevo dueño registrado",
                text: data.msg,
                icon: "success",
              });
            });
          }
        })
        .then((data) => {});
    });
  }
</script>
{% endblock %}

src/templates/superuser/settings.html
{% extends 'dashboard.html' %}

{% block sidenavbar %}
<li class="mb-4"><a href="/dashboard/superuser/metrics" class="block p-2 rounded hover:bg-blue-500">Métricas del sitio</a></li>
<li class="mb-4"><a href="/dashboard/superuser/register" class="block p-2 rounded hover:bg-blue-500">Registrar cliente</a></li>
<li class="mb-4"><a href="/dashboard/superuser/settings" class="block p-2 rounded hover:bg-blue-500">Ajustes</a></li>
{% endblock %}

{% block cont_dash %}
Settings
{% endblock %}